# This file is a template, and might need editing before it works on your project.
# Official docker image.
image: docker:latest

services:
  - docker:dind

before_script:
  - docker login -u "$DOCKER_USER" -p "$DOCKER_PASSWORD" # $CI_REGISTRY

build-master:
  stage: build
  script:
    - docker build --pull -t "$IMAGE_NAME" .
    - docker push "$IMAGE_NAME"
  only:
    - master

build:
  stage: build
  script:
    - docker build --pull -t "$IMAGE_NAME:$CI_COMMIT_REF_SLUG" .
    - docker push "$IMAGE_NAME:$CI_COMMIT_REF_SLUG"
  except:
    - master
